<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 16 Feb 2019 07:28:58 +0000
 */
$conf['title'] = '知识库';
$conf['lang'] = 'zh';
$conf['tagline'] = '个人知识管理';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['indexmenu']['skip_file'] = '/sidebar/';

// end auto-generated content 
