# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 16 Feb 2019 07:28:58 +0000
*               @ALL          1
*               @user         8
