<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Sat, 16 Feb 2019 07:28:58 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
